manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # Additional modules containing boards/shields/custom code can be listed here as well
    # See https://docs.zephyrprojec-t.org/3.2.0/develop/west/manifest.html#projects
    - name: infused-kim
      url-base: https://github.com/infused-kim
  projects:
    # - name: zmk
    #   remote: zmkfirmware
    #   revision: main
    #   import: app/west.yml
      - name: zmk
        remote: infused-kim
        revision: pr-testing/mouse_ps2_module_base
        import: app/west.yml
      - name: kb_zmk_ps2_mouse_trackpoint_driver
        remote: infused-kim
        revision: main
  self:
    path: config